#include <stdio.h>
#include <stdlib.h>
#define KB 1024

// Not yet quite sure about how I want to set up my struct for the CPU.

//6502

//struct CPU {
//  unsigned char zeroPage[100];
//  unsigned char stack[100];
//  unsigned char ram[600];
//  unsigned char IO[20];
//  unsigned char expRom[1980];
//  unsigned char sram[2000];
//  unsigned char lowPrgRom[4000];
//  unsigned char upPrgRom[4000];
//}
//}


// instruction name, address mode, address, length in bytes
const struct opcodes[151] = {
  {"BRK", "Implied", 0x00, 1},
  {"ORA", "Indirect X", 0x01, 2},
  {"ORA", "Zero Page", 0x05, 2},
  {"ASL", "Zero Page", 0x06, 2},
  {"PHP", "Implied", 0x08, 1},
  {"ORA", "Immediate", 0x09, 2},
  {"ASL", "Accumulator", 0x0A, 1},
  {"ORA", "Absolute", 0x0D, 3},
  {"ASL", "Absolute", 0x0E, 3},
  {"BPL", "Relative", 0x10, 2},
  {"ORA", "Indirect Y", 0x11, 2},
  {"ORA", "Zero Page X", 0x15, 1},
  {"ASL", "Zero Page X", 0x16, 2},
  {"CLC", "Implied", 0x18, 1},
  {"ORA", "Absolute Y", 0x19, 3},
  {"ORA", "Absolute X", 0x1D, 3},
  {"ASL", "Absolute X", 0x1E, 3},
  {"JSR", "Absolute", 0x20, 3},
  {"AND", "Indirect X", 0x21, 2},
  {"BIT", "Zero Page", 0x24, 2},
  {"AND", "Zero Page", 0x25, 2},
  {"ROL", "Zero Page", 0x26, 2},
  {"PLP", "Implied", 0x28, 1},
  {"AND", "Immediate", 0x29, 2},
  {"ROL", "Accumulator", 0x2A, 1},
  {"BIT", "Absolute", 0x2C, 3},
  {"AND", "Absolute", 0x2D, 3},
  {"ROL", "Absolute", 0x2E, 3},
  {"BMI", "Relative", 0x30, 2},
  {"AND", "Indirect Y", 0x31, 2},
  {"AND", "Zero Page X", 0x35, 2},
  {"ROL", "Zero Page X", 0x36, 2},
  {"SEC", "Implied", 0x38, 1},
  {"AND", "Absolute Y", 0x39, 3},
  {"AND", "Absolute X", 0x3D, 3},
  {"ROL", "Absolute X", 0x3E, 3},
  {"RTI", "Implied", 0x40, 1},
  {"EOR", "Indirect X", 0x41, 2},
  {"EOR", "Zero Page", 0x45, 2},
  {"LSR", "Zero Page", 0x46, 2},
  {"PHA", "Implied", 0x48, 1},
  {"EOR", "Immediate", 0x49, 2},
  {"LSR", "Accumulator", 0x4A, 1},
  {"JMP", "Absolute", 0x4C, 3},
  {"EOR", "Absolute", 0x4D, 3},
  {"LSR", "Absolute", 0x4E, 3},
  {"BVC", "Relative", 0x50, 2},
  {"EOR", "Indirect Y", 0x51, 2},
  {"EOR", "Zero Page X", 0x55, 2},
  {"LSR", "Zero Page X", 0x56, 2},
  {"CLI", "Implied", 0x58, 1},
  {"EOR", "Absolute Y", 0x59, 3},
  {"EOR", "Absolute X", 0x5D, 3},
  {"LSR", "Absolute X", 0x5E, 3},
  {"RTS", "Implied", 0x60, 1},
  {"ADC", "Indirect X", 0x61, 2},
  {"ADC", "Zero Page", 0x65, 2},
  {"ROR", "Zero Page", 0x66, 2},
  {"PLA", "Implied", 0x68, 1},
  {"ADC", "Immediate", 0x69, 2},
  {"ROR", "Accumulator", 0x6A, 1},
  {"JMP", "Indirect", 0x6C, 3},
  {"ADC", "Absolute", 0x6D, 3},
  {"ROR", "Absolute", 0x6E, 3},
  {"BVS", "Relative", 0x70, 2},
  {"ADC", "Indirect Y", 0x71, 2},
  {"ADC", "Zero Page X", 0x75, 2},
  {"ROR", "Zero Page X", 0x76, 2},
  {"SEI", "Implied", 0x78, 1},
  {"ADC", "Absolute Y", 0x79, 3},
  {"ADC", "Absolute X", 0x7D, 3},
  {"ROR", "Absolute X", 0x7E, 3},
  {"STA", "Indirect X", 0x81, 2},
  {"STY", "Zero Page", 0x84, 2},
  {"STA", "Zero Page", 0x85, 2},
  {"STX", "Zero Page", 0x86, 2},
  {"DEY", "Implied", 0x88, 1},
  {"TXA", "Implied", 0x8A, 1},
  {"STY", "Absolute", 0x8C, 3},
  {"STA", "Absolute", 0x8D, 3},
  {"STX", "Absolute", 0x8E, 3},
  {"BCC", "Relative", 0x90, 2},
  {"STA", "Indirect Y", 0x91, 2},
  {"STY", "Zero Page X", 0x94, 2},
  {"STA", "Zero Page X", 0x95, 2},
  {"STX", "Zero Page X", 0x96, 2},
  {"TYA", "Implied", 0x98, 1},
  {"STA", "Absolute Y", 0x99, 3},
  {"TXS", "Implied", 0x9A, 1},
  {"STA", "Absolute X", 0x9D, 3},
  {"LDY", "Immediate", 0xA0, 2},
  {"LDA", "Indirect X", 0xA1, 2},
  {"LDX", "Immediate", 0xA2, 2},
  {"LDY", "Zero Page", 0xA4, 2},
  {"LDA", "Zero Page", 0xA5, 2},
  {"LDX", "Zero Page", 0xA6, 2},
  {"TAY", "Implied", 0xA8, 1},
  {"LDA", "Immediate", 0xA9, 2},
  {"TAX", "Implied", 0xAA, 1},
  {"LDY", "Absolute", 0xAC, 3},
  {"LDA", "Absolute", 0xAD, 3},
  {"LDX", "Absolute", 0xAE, 3},
  {"BCS", "Relative", 0xB0, 2}, 
  {"LDA", "Indirect Y", 0xB1, 2},
  {"LDY", "Zero Page X", 0xB4, 2},
  {"LDA", "Zero Page X", 0xB5, 2},
  {"LDX", "Zero Page Y", 0xB6, 2},
  {"TSX", "Implied", 0xBA, 1},
  {"CLV", "Implied", 0xB8, 1},
  {"LDA", "Absolute Y", 0xB9, 3},
  {"LDY", "Absolute X", 0xBC, 3},
  {"LDA", "Absolute X", 0xBD, 3},
  {"LDX", "Absolute Y", 0xBE, 3},
  {"CPY", "Immediate", 0xC0, 2},
  {"CMP", "Indirect X", 0xC1, 2},
  {"CPY", "Zero Page", 0xC4, 2},
  {"DEX", "Implied", 0xCA, 1},
  {"CPY", "Absolute", 0xCC, 3},
  {"CMP", "Zero Page", 0xC5, 2},
  {"DEC", "Zero Page", 0xC6, 2},
  {"INY", "Implied", 0xC8, 1},
  {"CMP", "Immediate", 0xC9, 2},
  {"CMP", "Absolute", 0xCD, 3},
  {"DEC", "Absolute", 0xCE, 3},
  {"BNE", "Relative", 0xD0, 2},
  {"CMP", "Indirect Y", 0xD1, 2},
  {"CMP", "Zero Page X", 0xD5, 2},
  {"DEC", "Zero Page X", 0xD6, 2},
  {"CLD", "Implied", 0xD8, 1},
  {"CMP", "Absolute Y", 0xD9, 3},
  {"CMP", "Absolute X", 0xDD, 3},
  {"DEC", "Absolute X", 0xDE, 3},
  {"NOP", "Implied", 0xEA, 1},
  {"CPX", "Immediate", 0xE0, 2},
  {"SBC", "Indirect X", 0xE1, 2},
  {"CPX", "Zero Page", 0xE4, 2},
  {"SBC", "Zero Page", 0xE5, 2},
  {"INC", "Zero Page", 0xE6, 2},
  {"INX", "Implied", 0xE8, 1},
  {"SBC", "Immediate", 0xE9, 2},
  {"CPX", "Absolute", 0xEC, 3},
  {"SBC", "Absolute", 0xED, 3},
  {"INC", "Absolute", 0xEE, 3},
  {"BEQ", "Relative", 0xF0, 2},
  {"SBC", "Indirect Y", 0xF1, 2},
  {"SBC", "Zero Page X", 0xF5, 2},
  {"INC", "Zero Page X", 0xF6, 2},
  {"SED", "Implied", 0xF8, 1},
  {"SBC", "Absolute Y", 0xF9, 3},
  {"SBC", "Absolute X", 0xFD, 3},
  {"INC", "Absolute X", 0xFE, 3},
};
